name: blue-canvas

services:
  mariadb:
    image: mariadb:10.6.28@sha256:92e50059ea0a5965a33ef751970eab37d421b91ebbd01ac909039cffe159e574
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-blue_canvas}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-blue_canvas_dev}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-blue_canvas_root_dev}
      MARIADB_USER: ${MARIADB_USER:-blue_canvas}
    ports:
      - "127.0.0.1:${MARIADB_PORT:-3306}:3306"
    volumes:
      - mariadb106-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5m

volumes:
  mariadb106-data:
